[package]
name = "sustcsc-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.1"
tfhe = { version = "1.2.0", features = ["boolean", "integer", "nightly-avx512"] }
rayon = "1.10.0"


[profile.release]
opt-level = 3
