[package]
name = "sustcsc-rs-bonus"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = "0.16.1"
ndarray-rand = "0.15.0"
rand = "0.9.1"
pyo3 = { version = "0.21.0", features = ["auto-initialize"] }

[profile.release]
opt-level = 1
